In [1]:
# Importing

import tensorflow as tf

In [2]:
scalar=tf.constant(2) # 0 Dimension
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [3]:
vector=tf.constant([1,2]) # 1 Dimension
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [4]:
matrix=tf.constant([[1,2],[3,4]]) # 2 Dimensions
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [5]:
tensor=tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]]) # >2 Dimensions
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

In [6]:
unchange_tensor=tf.Variable([[[1,2],[3,4]],[[5,6],[7,8]]]) # Changable
unchange_tensor

<tf.Variable 'Variable:0' shape=(2, 2, 2) dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

In [7]:
unchange_tensor[0,0,0].assign(0)

<tf.Variable 'UnreadVariable' shape=(2, 2, 2) dtype=int32, numpy=
array([[[0, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

In [8]:
tf.random.Generator.from_seed(30)
normal_tensor=tf.random.normal((2,2,2))
normal_tensor

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[ 0.17709458, -0.28476387],
        [ 1.0869306 ,  1.5098499 ]],

       [[-0.05204318,  0.18493454],
        [-0.9942864 ,  0.16912152]]], dtype=float32)>

In [9]:
tf.random.Generator.from_seed(30)
uniform_tensor=tf.random.uniform((2,2,2))
uniform_tensor

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[0.56518126, 0.47163677],
        [0.86716235, 0.61836874]],

       [[0.27368677, 0.20903826],
        [0.449669  , 0.248528  ]]], dtype=float32)>

In [10]:
zero_tensor=tf.zeros((2,3,4))
zero_tensor

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [11]:
one_tensor=tf.ones((2,3,4))
one_tensor

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [12]:
random=tf.fill((2,3,4),30)
random

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[30, 30, 30, 30],
        [30, 30, 30, 30],
        [30, 30, 30, 30]],

       [[30, 30, 30, 30],
        [30, 30, 30, 30],
        [30, 30, 30, 30]]], dtype=int32)>

In [13]:
iden=tf.eye(5)
iden

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [14]:
tf.random.set_seed(30)
shuffle_tensor=tf.random.shuffle(iden)
shuffle_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [15]:
tf.size(iden)

<tf.Tensor: shape=(), dtype=int32, numpy=25>

In [16]:
iden[...,tf.newaxis] # Expanding the Dimension

<tf.Tensor: shape=(5, 5, 1), dtype=float32, numpy=
array([[[1.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [1.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [1.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [1.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [1.]]], dtype=float32)>

In [17]:
tf.expand_dims(iden,1)

<tf.Tensor: shape=(5, 1, 5), dtype=float32, numpy=
array([[[1., 0., 0., 0., 0.]],

       [[0., 1., 0., 0., 0.]],

       [[0., 0., 1., 0., 0.]],

       [[0., 0., 0., 1., 0.]],

       [[0., 0., 0., 0., 1.]]], dtype=float32)>

In [18]:
tf.random.set_seed(30)
A=tf.random.uniform((3,3),maxval=20,dtype=tf.int32)
B=tf.random.uniform((3,3),maxval=20,dtype=tf.int32)

In [19]:
C=tf.linalg.matmul(A,B) # Matrix Multplication
C

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[230, 336, 168],
       [416, 376, 260],
       [312, 470, 277]], dtype=int32)>

In [20]:
D=A@B # Python Operator for Matrix Multplication
D

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[230, 336, 168],
       [416, 376, 260],
       [312, 470, 277]], dtype=int32)>

In [21]:
tf.random.set_seed(30)
E=tf.random.uniform((2,3),maxval=20,dtype=tf.int32)
F=tf.random.uniform((2,3),maxval=20,dtype=tf.int32)

F_change=tf.reshape(F,(3,2))
F_transpose=tf.transpose(F)

F,F_change,F_transpose

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 9, 19, 13],
        [19,  1, 18]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 9, 19],
        [13, 19],
        [ 1, 18]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 9, 19],
        [19,  1],
        [13, 18]], dtype=int32)>)

In [22]:
G=E@F_change
H=E@F_transpose
G,H

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[119, 354],
        [188, 520]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[209, 336],
        [380, 376]], dtype=int32)>)

In [23]:
I=tf.tensordot(E,F_transpose,1) # Matrix Multplication
I

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[209, 336],
       [380, 376]], dtype=int32)>

In [24]:
tf.random.set_seed(30)
J=tf.random.uniform((2,3),maxval=20,dtype=tf.int32)
J_float=tf.cast(J,tf.float16)
J,J_float

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[11,  1,  7],
        [ 8,  8, 12]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=float16, numpy=
 array([[11.,  1.,  7.],
        [ 8.,  8., 12.]], dtype=float16)>)

In [25]:
tf.random.set_seed(30)
K=tf.random.uniform((20,),maxval=20,dtype=tf.int32)
K_max=tf.reduce_max(K)
K_min=tf.reduce_min(K)
K_mean=tf.reduce_mean(K)
K_sum=tf.reduce_sum(K)
K,K_max,K_min,K_mean,K_sum

(<tf.Tensor: shape=(20,), dtype=int32, numpy=
 array([11,  1,  7,  8,  8, 12, 18,  2,  7,  1,  8, 11, 15,  6,  4,  0, 13,
        12, 17, 14], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=18>,
 <tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=8>,
 <tf.Tensor: shape=(), dtype=int32, numpy=175>)

In [26]:
import tensorflow_probability as tfp
K_std=tf.math.reduce_std(tf.cast(K,dtype=tf.float32))
K_var=tf.math.reduce_variance(tf.cast(K,dtype=tf.float32))
K_var1=tfp.stats.variance(tf.cast(K,dtype=tf.float32))
K_std,K_var,K_var1

(<tf.Tensor: shape=(), dtype=float32, numpy=5.242852>,
 <tf.Tensor: shape=(), dtype=float32, numpy=27.4875>,
 <tf.Tensor: shape=(), dtype=float32, numpy=27.4875>)

In [27]:
min_pos=tf.argmin(K)
max_pos=tf.argmax(K)
min_ele=K[tf.argmin(K)]
max_ele=K[tf.argmax(K)]
K,min_pos,max_pos,min_ele,max_ele

(<tf.Tensor: shape=(20,), dtype=int32, numpy=
 array([11,  1,  7,  8,  8, 12, 18,  2,  7,  1,  8, 11, 15,  6,  4,  0, 13,
        12, 17, 14], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int64, numpy=15>,
 <tf.Tensor: shape=(), dtype=int64, numpy=6>,
 <tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=18>)

In [28]:
tf.random.set_seed(30)
L=tf.random.uniform((2,3,1),maxval=20,dtype=tf.int32)
L_reduce=tf.squeeze(L)
L,L_reduce

(<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
 array([[[11],
         [ 1],
         [ 7]],
 
        [[ 8],
         [ 8],
         [12]]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[11,  1,  7],
        [ 8,  8, 12]], dtype=int32)>)

In [29]:
M=tf.constant([1,2,3])
M_one_hot=tf.one_hot(M,3)
M,M_one_hot

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.]], dtype=float32)>)

In [30]:
tf.random.set_seed(30)
N=tf.random.uniform((2,3,4),maxval=20,dtype=tf.int32)
N_squ=tf.square(tf.cast(N,dtype=tf.float32))
N_sqrt=tf.sqrt(tf.cast(N,dtype=tf.float32))
N_log=tf.math.log(tf.cast(N,dtype=tf.float32))
N,N_squ,N_sqrt,N_log

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[11,  1,  7,  8],
         [ 8, 12, 18,  2],
         [ 7,  1,  8, 11]],
 
        [[15,  6,  4,  0],
         [13, 12, 17, 14],
         [10, 15,  3,  7]]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
 array([[[121.,   1.,  49.,  64.],
         [ 64., 144., 324.,   4.],
         [ 49.,   1.,  64., 121.]],
 
        [[225.,  36.,  16.,   0.],
         [169., 144., 289., 196.],
         [100., 225.,   9.,  49.]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
 array([[[3.3166246, 1.       , 2.6457512, 2.828427 ],
         [2.828427 , 3.4641016, 4.2426405, 1.4142135],
         [2.6457512, 1.       , 2.828427 , 3.3166246]],
 
        [[3.8729832, 2.4494896, 2.       , 0.       ],
         [3.6055512, 3.4641016, 4.1231055, 3.7416573],
         [3.1622777, 3.8729832, 1.7320508, 2.6457512]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
 array([[[2.3978953, 0.     

In [31]:
tf.config.list_physical_devices() # Details about the CPU , GPU , TPU

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [32]:
!nvidia-smi

Sat Jan  4 13:26:36 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P0              28W /  70W |    107MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--